# Generated by Django 4.1 on 2022-09-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_options_profile_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tel',
            field=models.CharField(default='+998910028174', max_length=500, verbose_name='Tel Nbm'),
            preserve_default=False,
        ),
    ]
