# Generated by Django 4.1 on 2022-09-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_img',
            field=models.FileField(upload_to='static/account/img'),
        ),
    ]
