# Generated by Django 4.1 on 2022-09-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_prof_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_img',
            field=models.ImageField(upload_to='static/account/img', verbose_name='Аватарка'),
        ),
    ]
