# Generated by Django 4.1 on 2022-09-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(default='somestr', max_length=1000, verbose_name='Instagram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='prof_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/account/img', verbose_name='Аватарка'),
        ),
    ]
