# Generated by Django 4.1 on 2022-10-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tel Nbm'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wk',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='WK'),
        ),
    ]
