# Generated by Django 4.1 on 2022-10-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_profile_facebook_alter_profile_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/accounts/profile'),
        ),
    ]
