# Generated by Django 4.1 on 2022-10-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_profile_prof_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_img',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
