# Generated by Django 4.1 on 2022-10-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_profile_prof_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Tel Nbm'),
        ),
    ]
