# Generated by Django 4.1 on 2022-11-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_profile_facebook_alter_profile_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, default='#', max_length=1000, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, default='#', max_length=13, null=True, verbose_name='Tel Nbm'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, default='#', max_length=1000, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wk',
            field=models.CharField(blank=True, default='#', max_length=1000, null=True, verbose_name='WK'),
        ),
    ]
