# Generated by Django 4.1 on 2022-09-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_answers_replys_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribes',
            name='email',
            field=models.EmailField(max_length=300, verbose_name='Email'),
        ),
    ]
