# Generated by Django 4.1 on 2022-09-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_subscribes_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
            preserve_default=False,
        ),
    ]
