# Generated by Django 4.1 on 2022-10-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.FloatField(default=33444.6, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
