# Generated by Django 4.1 on 2022-10-12 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_remove_cart_total_alter_cart_name_alter_cart_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='prim_key',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
