# Generated by Django 4.1 on 2022-10-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_wishlist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='file',
            field=models.FileField(default='ssssfs', upload_to='static/main/img/cart_img', verbose_name='Img'),
            preserve_default=False,
        ),
    ]
