# Generated by Django 4.1 on 2022-10-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_cart_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
