# Generated by Django 4.1 on 2022-10-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='post_category',
            field=models.CharField(choices=[("Men's Shirts", "Men's Shirts"), ("Men's Blazers", "Men's Blazers"), ('Underwear', 'Underwear'), ('Underwear', 'Underwear'), ('Underwear', 'Underwear'), ("women's Blazers", "women's Blazers"), ('skirt', 'skirt'), ('Shoes', 'Shoes'), ("Women's shirts", "Women's shirts"), ('Pijamas', 'Pijamas'), ('Hoodies', 'Hoodies'), ('Caps', 'Caps'), ('Panama hats', 'Panama hats'), ('Rings', 'Rings'), ('Bracelets', 'Bracelets'), ('Wristwatch', 'Wristwatch'), ('Jeans', 'Jeans')], default=1, max_length=500, verbose_name='Post_category'),
            preserve_default=False,
        ),
    ]
