# Generated by Django 4.1 on 2022-10-15 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_products_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='post_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.postcategories'),
        ),
    ]
