# Generated by Django 4.1 on 2022-10-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_comments_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
