# Generated by Django 4.1 on 2022-10-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_delete_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
