# Generated by Django 4.1 on 2022-10-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_comments_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='prof',
        ),
    ]
