# Generated by Django 4.1 on 2022-10-23 10:07

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_comments_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='file',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='cart_img', verbose_name='Img'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='prod-imgs', verbose_name='Файл'),
        ),
    ]
