# Generated by Django 4.1 on 2022-10-29 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_cart_file_alter_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='qty',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Product quntity'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Price'),
        ),
    ]
