# Generated by Django 4.1 on 2022-10-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_products_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='post_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.postcategories'),
        ),
    ]
