# Generated by Django 4.1 on 2022-11-02 16:45

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_comments_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='ctg_avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='ctg_image', verbose_name='Category Avatar'),
        ),
    ]
