# Generated by Django 4.1 on 2022-11-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_categories_desckription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='desckription',
        ),
        migrations.AddField(
            model_name='categories',
            name='deskription',
            field=models.TextField(default='time', verbose_name='Deskription'),
            preserve_default=False,
        ),
    ]
