# Generated by Django 4.1 on 2022-11-06 10:20

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_categories_desckription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='prod-imgs'),
        ),
    ]
