# Generated by Django 4.1 on 2022-11-07 11:15

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_products_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='prod-imgs'),
        ),
    ]
