# Generated by Django 4.1 on 2022-11-07 11:32

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_products_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='default_img.png', upload_to='prod-imgs'),
        ),
    ]
