# Generated by Django 4.1 on 2022-11-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_products_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Product name'),
        ),
    ]
