# Generated by Django 4.1 on 2022-11-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_products_prod_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Atribut name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributs', to='main.categories')),
            ],
        ),
        migrations.CreateModel(
            name='AtributParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Param name')),
                ('atr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametrs', to='main.atributs')),
            ],
        ),
    ]
