# Generated by Django 4.1 on 2022-11-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_atributs_atributparams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atributs',
            name='category',
        ),
        migrations.AddField(
            model_name='categories',
            name='atributs',
            field=models.ManyToManyField(to='main.atributs'),
        ),
    ]
