# Generated by Django 4.1 on 2022-11-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_colors_hex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colors',
            old_name='hex',
            new_name='color',
        ),
    ]
