# Generated by Django 4.1 on 2022-11-13 16:20

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_rename_hex_colors_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='qty',
        ),
        migrations.AddField(
            model_name='productvariants',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='price',
            field=models.FloatField(default=25.0, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariants',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Product quntity'),
        ),
    ]
