# Generated by Django 4.1 on 2022-11-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_remove_products_qty_productvariants_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.productvariants'),
        ),
    ]
