# Generated by Django 4.1 on 2022-11-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_files_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='main.products'),
        ),
    ]
