# Generated by Django 4.1 on 2022-11-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_productvariants_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
    ]
