# Generated by Django 4.1 on 2022-11-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.colors'),
        ),
    ]
