# Generated by Django 4.1 on 2022-11-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_productvariants_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='atributs',
            field=models.ManyToManyField(blank=True, null=True, to='main.atributs'),
        ),
    ]
