# Generated by Django 4.1 on 2022-11-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_categories_atributs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
    ]
