# Generated by Django 4.1 on 2022-11-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_remove_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(to='main.colors'),
        ),
    ]
