# Generated by Django 4.1 on 2022-09-19 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_answers_replys_to'),
        ('palpay', '0002_alter_orders_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(choices=[('Ташкент', 'Ташкент'), ('Самарканд', 'Самарканд'), ('Бухара', 'Бухара'), ('Хива', 'Хива'), ('Шахрисабз', 'Шахрисабз'), ('Муйнак', 'Муйнак'), ('Заамин', 'Заамин'), ('Термез', 'Термез'), ('Гулистан', 'Гулистан'), ('Нукус', 'Нукус'), ('Наманган', 'Наманган'), ('Карши', 'Карши'), ('Навои', 'Навои'), ('Коканд', 'Коканд'), ('Андижан', 'Андижан'), ('Фергана', 'Фергана')], max_length=500, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
