# Generated by Django 4.1 on 2022-09-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpay', '0004_orderedproducts_quantity_orderedproducts_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cash',
            field=models.BooleanField(default=False, verbose_name='Pay with cash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='payme',
            field=models.BooleanField(default=False, verbose_name='Pay by Payme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderedproducts',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
    ]
