# Generated by Django 4.1 on 2022-09-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpay', '0005_orders_cash_orders_payme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cash',
            field=models.BooleanField(default=False, verbose_name='Pay with cash'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payme',
            field=models.BooleanField(default=False, verbose_name='Pay by Payme'),
        ),
    ]
