# Generated by Django 4.1 on 2022-09-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpay', '0006_alter_orders_cash_alter_orders_payme'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Performed', 'Performed'), ('Delivered', 'Delivered')], default='Accepted', max_length=500, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='cash',
            field=models.BooleanField(default=True, verbose_name='Pay with cash'),
        ),
    ]
