# Generated by Django 4.1 on 2022-09-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpay', '0008_orders_order_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item_count',
            field=models.IntegerField(default=5, verbose_name='Products Count'),
            preserve_default=False,
        ),
    ]
