# Generated by Django 4.1 on 2022-09-25 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('palpay', '0010_alter_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
