# Generated by Django 4.1 on 2022-09-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpay', '0011_orders_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='session',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Session Id'),
        ),
    ]
