# Generated by Django 4.1 on 2022-09-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpay', '0013_orderedproducts_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproducts',
            name='total',
            field=models.FloatField(default=13.0, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
