# Generated by Django 4.1 on 2022-10-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpay', '0014_orderedproducts_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='adres',
            field=models.CharField(max_length=255, verbose_name='Your adress'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(choices=[('Ташкент', 'Ташкент'), ('Самарканд', 'Самарканд'), ('Бухара', 'Бухара'), ('Хива', 'Хива'), ('Шахрисабз', 'Шахрисабз'), ('Муйнак', 'Муйнак'), ('Заамин', 'Заамин'), ('Термез', 'Термез'), ('Гулистан', 'Гулистан'), ('Нукус', 'Нукус'), ('Наманган', 'Наманган'), ('Карши', 'Карши'), ('Навои', 'Навои'), ('Коканд', 'Коканд'), ('Андижан', 'Андижан'), ('Фергана', 'Фергана')], max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='item_count',
            field=models.IntegerField(default=1, verbose_name='Products Count'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Your name'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Session Id'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Performed', 'Performed'), ('Delivered', 'Delivered')], max_length=255, verbose_name='Status'),
        ),
    ]
