# Generated by Django 4.1 on 2022-10-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpay', '0019_alter_orderedproducts_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='img',
            field=models.FileField(upload_to='static/main/img/order_img'),
        ),
    ]
