# Generated by Django 4.1 on 2022-10-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palpay', '0020_alter_orderedproducts_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='palpay.orders'),
        ),
    ]
