# Generated by Django 4.1 on 2022-10-23 10:07

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('palpay', '0021_alter_orderedproducts_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='img',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='order_products_img'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_img',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='order_img'),
        ),
    ]
