# Generated by Django 4.1 on 2022-11-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpay', '0023_alter_orderedproducts_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.EmailField(default='exit@gmail.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
