# Generated by Django 4.1 on 2022-11-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palpay', '0024_orders_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='size',
            field=models.CharField(max_length=255, verbose_name='Size'),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('comment', models.CharField(max_length=255, verbose_name='Comment')),
                ('date', models.DateField(verbose_name='Update Date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='palpay.orders')),
            ],
        ),
    ]
