# Generated by Django 4.1 on 2022-11-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpay', '0026_alter_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Usernme'),
        ),
    ]
