# Generated by Django 4.1 on 2022-11-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpay', '0028_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Performed', 'Performed'), ('Delivered', 'Delivered'), ('Canseled', 'Canseled')], default='Accepted', max_length=255, verbose_name='Status'),
        ),
    ]
