# Generated by Django 4.1 on 2022-11-19 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpay', '0032_orders_ship_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingtype',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price'),
        ),
    ]
